
  spring:
    datasource:
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///stu?unicode=true&characterEncoding=utf-8
      password: root
    mvc:
      view:
        prefix: /
        suffix: .jsp